### ISSUE TITLE
Can't pass test!

### ISSUE THREAD

**Issue by erinmilling** [acgd-webdev-3/animated-clock#19]
<img width="655" alt="screen shot 2016-01-22 at 1 57 36 pm" src="https://cloud.githubusercontent.com/assets/10464609/12520053/455ad2a2-c110-11e5-87ce-421d4bd458e1.png">
<img width="349" alt="screen shot 2016-01-22 at 1 57 31 pm" src="https://cloud.githubusercontent.com/assets/10464609/12520054/4569780c-c110-11e5-943d-6992ea0ef3bd.png">

I showed you in class and tried passing again with no luck.. :(
@thomasjbradley

**Comment by thomasjbradley** [comment]
There needs to be some extra space around things, like this:

```css
@keyframes spin {

  0% {}
  
  100% {}

}
```
